Repository plouc/nivo, pull requests merged in 2025-05, with the labels that each got.

#2744 feat(axes): allow axes style overrides
  packages/axes/src/canvas.ts
  packages/axes/src/components/Axis.tsx
  packages/axes/src/components/AxisTick.tsx
  packages/axes/src/types.ts
  packages/polar-axes/src/CircularAxis.tsx
  packages/polar-axes/src/CircularAxisTick.tsx
  packages/polar-axes/src/RadialAxis.tsx
  packages/polar-axes/src/RadialAxisTick.tsx
  packages/polar-axes/src/types.ts
  packages/theming/src/extend.ts
  packages/theming/src/hooks.ts
  storybook/stories/line/Line.stories.tsx
  storybook/stories/line/LineCanvas.stories.tsx
  storybook/stories/line/shared.ts
  website/src/data/components/line/meta.yml
  website/src/lib/chart-properties/axes.ts
  website/src/lib/componentProperties.ts
Labels: :triangular_ruler: axes

#1978 @nivo/rects and @nivo/icicles package
  packages/icicles/LICENSE.md
  packages/icicles/README.md
  packages/icicles/package.json
  packages/icicles/src/Icicles.tsx
  packages/icicles/src/IciclesTooltip.tsx
  packages/icicles/src/Rects.tsx
  packages/icicles/src/ResponsiveIcicles.tsx
  packages/icicles/src/hooks.ts
  packages/icicles/src/index.ts
  packages/icicles/src/props.ts
  packages/icicles/src/types.ts
  packages/icicles/stories/icicles.stories.tsx
  packages/icicles/tests/.eslintrc.yml
  packages/icicles/tests/Icicles.test.tsx
  packages/icicles/tsconfig.json
  packages/rects/LICENSE.md
  packages/rects/README.md
  packages/rects/package.json
  packages/rects/src/RectShape.tsx
  packages/rects/src/RectsLayer.tsx
  packages/rects/src/centers.ts
  packages/rects/src/index.ts
  packages/rects/src/rect_labels/RectLabel.tsx
  packages/rects/src/rect_labels/RectLabelsLayer.tsx
  packages/rects/src/rect_labels/index.ts
  packages/rects/src/rect_labels/props.ts
  packages/rects/src/types.ts
  packages/rects/src/useRectsTransition.ts
  packages/rects/tsconfig.json
  packages/static/package.json
  packages/static/src/mappings/icicles.ts
  packages/static/src/mappings/index.ts
  packages/static/src/samples/index.ts
  tsconfig.monorepo.json
  website/package.json
  website/src/@types/file_types.d.ts
  website/src/components/home/Home.tsx
  website/src/components/home/HomeIciclesDemo.tsx
  website/src/components/home/index.ts
  website/src/components/icons/IciclesIcon.tsx
  website/src/components/icons/Icons.tsx
  website/src/data/components/icicles/mapper.tsx
  website/src/data/components/icicles/meta.yml
  website/src/data/components/icicles/props.ts
  website/src/data/nav.ts
  website/src/pages/icicles/api.tsx
  website/src/pages/icicles/index.js
  website/src/pages/internal/home-demos.tsx
Labels: pinned

#2752 Improve a11y for @nivo/icicle
  cypress/src/components/icicle/Icicle.cy.tsx
  cypress/src/components/icicle/IcicleHtml.cy.tsx
  packages/core/index.d.ts
  packages/icicle/README.md
  packages/icicle/src/Icicle.tsx
  packages/icicle/src/IcicleHtml.tsx
  packages/icicle/src/IcicleNodes.tsx
  packages/icicle/src/IcicleTooltip.tsx
  packages/icicle/src/defaults.ts
  packages/icicle/src/hooks.ts
  packages/icicle/src/types.ts
  packages/rects/src/RectNodeHtml.tsx
  packages/rects/src/RectNodeSvg.tsx
  packages/rects/src/RectNodeWrapper.tsx
  packages/rects/src/RectNodes.tsx
  packages/rects/src/hooks.ts
  packages/rects/src/index.ts
  packages/rects/src/labels/RectLabelHtml.tsx
  packages/rects/src/labels/RectLabelSvg.tsx
  packages/rects/src/labels/RectLabels.tsx
  packages/rects/src/labels/types.ts
  packages/rects/src/types.ts
  packages/rects/src/useRectAnchorsTransition.ts
  packages/rects/src/useRectsTransition.ts
  pnpm-lock.yaml
  storybook/package.json
  storybook/stories/icicle/BonsaisIcicle.tsx
  storybook/stories/icicle/Icicle.stories.tsx
  storybook/stories/icicle/IcicleHtml.stories.tsx
  storybook/stories/icicle/shared.tsx
  storybook/stories/internal/KeyLogger.tsx
  storybook/stories/internal/helpers.ts
  storybook/stories/rects/RectsNodes.stories.tsx
  website/src/data/components/bar/props.ts
  website/src/data/components/icicle/mapper.tsx
  website/src/data/components/icicle/meta.yml
  website/src/data/components/icicle/props.ts
  website/src/lib/chart-properties/interactivity.ts
  website/src/pages/icicle/html.tsx
  website/src/pages/icicle/index.tsx
Labels: a11y
